<a href="https://colab.research.google.com/github/Subhashree-2004/Subhashree_2201206070/blob/main/PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('wELCOME TO PYTHON PROGRAMMING')

wELCOME TO PYTHON PROGRAMMING


In [ ]:
print('Hello!!!',end='')
print("CSE")

Hello!!!CSE


In [ ]:
a=10
print("a=",a)

a= 10


In [ ]:
n=input('enter your name')
print('myself',n)

enter your name shree
myself  shree


In [ ]:
a=int(input('Enter 1st no'))
b=int(input('Enter 2nd no'))
c=a+b
print('a+b=',c)

Enter 1st no21
Enter 2nd no12
a+b= 33


In [ ]:
a=input('Enter 1st no')
b=input('Enter 2nd no')
c=a+b
print('a+b=',c)

Enter 1st no22
Enter 2nd no11
a+b= 2211


In [ ]:
a=100
b=10.55
c='ABIT'
d=True
print('Type of a=',type(a))
print('Type of b=',type(b))
print('Type of c=',type(c))
print('Type of d=',type(d))

Type of a= <class 'int'>
Type of b= <class 'float'>
Type of c= <class 'str'>
Type of d= <class 'bool'>


In [ ]:
#Complex Number
a=12+15j
print('a=',a)
print(a.real)
print(a.imag)

a= (12+15j)
12.0
15.0


In [ ]:
a=0b111
print('a=',a)
b=0xaa
print('b=',b)

a= 7
b= 170


In [ ]:
a=2
b=3
c=a+b
print('a+b',c)
d=a-b
print('a-b',d)
e=a*b
print('a*b',e)
f=a/b
print('a/b',f)
g=a**b
print('a**b',g)
h=a//b
print('a//b',h)

a+b 5
a-b -1
a*b 6
a/b 0.6666666666666666
a**b 8
a//b 0


In [ ]:
a=8
b=5
c=a!=b
print('a!=b',c)
d=a==b
print('a==b',d)
e=a<<b
print('a<<b',e)
f=a>>b
print('a>>b',f)
g=a&b
print('a&b',g)
h=a++b
print('a++b',h)
i=a--b
print('a--b',i)

a!=b True
a==b False
a<<b 256
a>>b 0
a&b 0
a++b 13
a--b 13


In [ ]:
a=5
b=8
d=a is b
print('a is b',d)
d=a is not b
print('a is not b',d)

a is b False
a is not b True


In [ ]:
# in operator
a="Hello!!"
b='l'
c=b in a
print('b in a',d)
d=b not in a
print('b not in a',d)

b in a True
b not in a False


In [ ]:
# intput a no and check even.
a=int(input('Enter a number'))
if a%2==0:
  print('Even no')
else:
 print('Odd no')

Enter a number45
Odd no


In [ ]:
a=int(input('Enter 1st no'))
b=int(input('Enter 2nd no'))
if a>=b:
 print('a is maximum')
 print('b is minimum')
else:
   print('a is minimum')
   print('b is maximum')

Enter 1st no12
Enter 2nd no20
a is minimum
b is maximum


In [ ]:
num=int(input("Enter the no"))
if num==10:
  print('Num is equal to 10')
elif num==50:
  print('Num is equal to 50')
else:
  print('Wrong no')

Enter the no10
Num is equal to 10


In [ ]:
str="PYTHON"
for i in str:
  print(i)

P
Y
T
H
O
N


In [ ]:
for i in range(1,11):
  print(i,end='')


12345678910

In [ ]:
n=int(input('Enter the no'))
c=0
for i in  range(1,n+1):
 if (n%2!=0):
  c=c+1
  print(i,end=',')
print('no of odd',c)

Enter the no15
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,no of odd 15


In [ ]:
#while loop
n=1
while n<=10:
 print(n)
 n=n+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#while loop
num=int(input('Enter the nos'))
rev=0
while num!=0:
  d=num%10
  rev=rev*10+d
  num//=10
  print('Reverse is'+str(rev))


Enter the nos 765893
Reverse is3
Reverse is39
Reverse is398
Reverse is3985
Reverse is39856
Reverse is398567


In [ ]:
rows=6
for i in range(rows):
  for j in range(i):
    print(i,end='')
  print('')


1
22
333
4444
55555


In [ ]:
rows=6
b=0
for i in range(rows,0,-1):
  b += 1
  for j in range(1,i,+1):
    print(b,end='')
  print('\r')

11111
2222
333
44
5



In [ ]:
n=5
for i in range(n,0,-1):
  b=i
  for j in range(0,i):
    print(b,end='')
  print('\r')

55555
4444
333
22
1


In [ ]:
for i in range(5,0,-1):
  for j in range(i,6):
    print(i,end='')
  print('')

5
44
333
2222
11111


In [ ]:
rows=6
for i in range(rows,0,-1):
  for j in range(0,i+1):
    print(j,end='')
  print('')

0123456
012345
01234
0123
012
01


In [ ]:
rows=5
num=rows
for i in range(rows,0,-1):
  for j in range(0,i):
    print(num,end='')
  print('')

55555
5555
555
55
5


In [ ]:
rows=6
for i in range(1,rows):
  for j in range(i,0,-1):
    print(j,end='')
  print('')

1
21
321
4321
54321


In [ ]:
rows=8
for i in range(1,rows+1):
  for j in range(1,i+1):
    sq=i*j
    print(i*j,end=" ")
  print('\r')

1 
2 4 
3 6 9 
4 8 12 16 
5 10 15 20 25 
6 12 18 24 30 36 
7 14 21 28 35 42 49 
8 16 24 32 40 48 56 64 


In [ ]:
rows=70
for i in range(65,rows):
  for j in range(65,i+1):
    print(chr(i),end=" ")
  print(" ")

A  
B B  
C C C  
D D D D  
E E E E E  


In [ ]:
rows=6
for i in range(1,6):
  print(str(i)*(i))

for i in range(4,0,-1):
  print(str(i)*(i))

1
22
333
4444
55555
4444
333
22
1


In [ ]:
for i in range(5,0,-1):
  print(str(i)*(i))
for i in range(1,6):
  print(str(i)*(i))

55555
4444
333
22
1
1
22
333
4444
55555


In [ ]:
def pattern(n):
  for i in range(1,n+1):
    print(str(i)*(n-i+1))
  for i in range(n-1,0,-1):
   print(str(i)*(n-i+1))
pattern(5)

11111
2222
333
44
5
44
333
2222
11111


In [ ]:
rows=6
l=2*rows-2
for i in range(0,rows):
  for j in range(0,l):
    print(end=" ")
  l=l-2
  for j in range(0,i+1):
    print("*",end=" ")
  print("")

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 
* * * * * * 


In [ ]:
def right_align_pyramid(rows):
  for i in range(1,rows+1):
    print(" "*(rows-1)+"#"*(2*i-1))
right_align_pyramid(5)

    #
    ###
    #####
    #######
    #########


In [ ]:
for var in "ABIT":
  if var =="B":
    continue
  print(var)

A
I
T


In [ ]:
for i in range(10):
  print(i)
  if i==2:
    break

0
1
2


In [ ]:
# abs()
x=abs(-4.6)
print(x)

4.6


In [ ]:
# all()
list=[0,2,2]
a=all(list)
print(a)

False


In [ ]:
# any()
tuple=[0,1,False]
a=any(tuple)
print(a)

True


In [ ]:
# ascii()
a=ascii("Shree")
print(a)

'Shree'


In [ ]:
# bin()
a=bin(30)
print(a)

0b11110


In [ ]:
# b00l()
a=bool(22)
print(a)

True


In [ ]:
# bytearray()
a=bytearray(22)
print(a)

bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')


In [ ]:
# bytes()
a=bytes(22)
print(a)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


In [ ]:
# callable()
b=5
print(callable(b))

False


In [ ]:
# chr()
a=chr(87)
print(a)

W


In [ ]:
# complex()
a=complex(2,7)
print(a)

(2+7j)


In [ ]:
# compile()
a=compile('print(45)','test','eval')
exec(a)

45


In [ ]:
# delattr()
class user:
name="Subhu"
mob=845689999
country="India"
delattr( person,"age")

SyntaxError: invalid syntax (<ipython-input-24-bb0aaa453f9e>, line 5)

In [ ]:
# user defined function
def show():
 print("Shree")
show()

Shree


In [ ]:
# passing parameters in user defind function
def ADD(a,b):
  c=a+b
  print('Sum of two nos',c)
ADD(10,20)


Sum of two nos 30


In [ ]:
# passing parameters in user defind function using keyboard
def ADD(a,b):
  c=a+b
  print('Sum of two nos',c)
p=int(input('Enter first no'))
q=int(input('Enter second no'))
ADD(p,q)


Enter first no20
Enter second no10
Sum of two nos 30


In [ ]:
# using return statement in user defind function
def sumofn(n):
  s=0
  for i in range(1,n+1):
    s=s+i
  return(s)
m=int(input('Enter n:'))
print('Sum of n=',sumofn(m))

Enter n:15
Sum of n= 120



1 
2 2 
3 3 3 
4 4 4 4 


In [ ]:
p=int(input('Enter the no'))
c=1
for i in range(p+1):
  for j in range (1,i+1):
     print(c,end=" ")
     c=c+1
  print()

Enter the no 5

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [ ]:
list=['P','Y','T','H','O','N']
print(list)

['P', 'Y', 'T', 'H', 'O', 'N']


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[2:6])

[30, 40, 50, 60]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[:4])

[10, 20, 30, 40]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[4:])

[50, 60, 70, 80, 90]


In [ ]:
# all()
list=["apple","orange","patato","tamato"]
a=all(list)
print(a)

True


In [ ]:
list=['Patato','Tomato','Apple','Orange']
print(list)
print(type(list))

['Patato', 'Tomato', 'Apple', 'Orange']
<class 'list'>


In [ ]:
list=['Patato','Tomato','Apple','Orange']
print(list)
print(len(list))

['Patato', 'Tomato', 'Apple', 'Orange']
4


In [ ]:
list=['100']
list2=['10.55']
list3=['ABIT']
list4=['True']
print('Type of 1=',type(list))
print('Type of 2=',type(list2))
print('Type of 3=',type(list3))
print('Type of 4=',type(list4))

Type of 1= <class 'list'>
Type of 2= <class 'list'>
Type of 3= <class 'list'>
Type of 4= <class 'list'>


In [ ]:
list1=["subha","shake","bluri"]
list2=[1,2,3]
list3=[True,False,True]
list4=[123,"payton sahi",True]
print(list1)
print(list2)
print(list3)
print(list4)

['subha', 'shake', 'bluri']
[1, 2, 3]
[True, False, True]
[123, 'payton sahi', True]


In [ ]:
list1=["subha","shake","bluri"]
list2=[1,2,3]
list3=[True,False,True]
list4=[123,"payton sahi",True]
print(list1[2])
print(list2[-2])
print(list3[-1])
print(list4[1])

bluri
2
True
payton sahi


In [ ]:
list1=["subha","shake","lovely"]
list2=[1,2,3]
list3=[True,False,True]
list4=[123,"payton sahi",True]
print(list1[2])
print(list2[1:2])
print(list3[1:3])
print(list4[-1])

lovely
[2]
[False, True]
True


In [ ]:
list1=["subha","shake","bluri"]
list2=[1,2,3]
list3=[True,False,True]
list4=[123,"payton sahi",True]
if("subha"==list1):
  print("item in the list")
else:
  print("item doesn't in the list")

item doesn't in the list


In [ ]:
list=['s','h','r','e','e']
list[2]='subha'
list1=['Rout']
list.insert(3,"shree")
list.append('su')
list.extend(list1)
list.remove('shree')
list.pop(2)
list.pop()
del list[3]
list.clear()
print(list)

[]


In [ ]:
list=[1,2,3,4,5,6]
for i in list:
  print(i)

1
2
3
4
5
6


In [ ]:
list1=[1,2,3,4,5,6,7]
i=1
while(i<len(list1)):
  print(list1[i])
  i=i+1

2
3
4
5
6
7


In [ ]:
def factorial(x):
  if x==1:
   return 1
  else:
   return(x*factorial(x-1))
num=3
print("The factorial of",num,"is",factorial(num))


The factorial of 3 is 6


In [ ]:
import math
pie=math.pi
print("The value of pie is",pie)

The value of pie is 3.141592653589793


In [ ]:
import random
import math
for i in range(5):
  print(random.randint(1,25))
print(math.pi)


8
11
16
22
19
3.141592653589793


In [ ]:
import math as m
print(m.pi)
print(m.e)

3.141592653589793
2.718281828459045


In [ ]:
from math import pow
print(pow(2,5))

32.0


In [ ]:
from random import randint
for i in range(10):
  print(randint(1,25))

20
14
4
22
13
10
24
11
20
3


In [ ]:
list=['I','LOVE','PYTHON']
list1=[1,2,3,4,5,6]
list2=['PYTHON',29,5.6,'is','a','b']
list,list1,list2

(['I', 'LOVE', 'PYTHON'],
 [1, 2, 3, 4, 5, 6],
 ['PYTHON', 29, 5.6, 'is', 'a', 'b'])

In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[::])
print(list[::2])
print(list[1:3])
print(list[2:7:2])
print(list[-3:])
print(list[-2:3])
print(list[::-2])
print(list[2:-4])

[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 30, 50, 70, 90]
[20, 30]
[30, 50, 70]
[70, 80, 90]
[]
[90, 70, 50, 30, 10]
[30, 40, 50]


In [ ]:
list=[10,21,30,45,50,63,78,80,90]
list[0]=1
print(list)
list[1:4]=[2,3,4]
print(list)
list[2]='Shree'
print(list)
list[3:5]='abc'
print(list)

[1, 21, 30, 45, 50, 63, 78, 80, 90]
[1, 2, 3, 4, 50, 63, 78, 80, 90]
[1, 2, 'Shree', 4, 50, 63, 78, 80, 90]
[1, 2, 'Shree', 'a', 'b', 'c', 63, 78, 80, 90]


In [ ]:
list=[10,20,40,50,60,70,80,90]
del list[0]
print(list)
del list[1:4]
print(list)
del list[::2]
print(list)

[20, 40, 50, 60, 70, 80, 90]
[20, 70, 80, 90]
[70, 90]


In [ ]:
list=[1,2,3,4,5]
print(list*4)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
list=[1,2,3,4]
list1=[5,6,7,8]
print(list+list1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
list=[1,2,3,4]
for i in list:
 print(i)

1
2
3
4


In [ ]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
if __name__ == "__main__":
    elements = input("Enter elements separated by space: ").split()
    elements = [int(e) for e in elements]
    bubble_sort(elements)
    print("Sorted array:", elements)

Enter elements separated by space: 5 2 3 7 99 33 71 57
Sorted array: [2, 3, 5, 7, 33, 57, 71, 99]


In [ ]:
unsorted_list={5,2,3,7,99,33,71,57}
sorted_list=sorted(unsorted_list)
print("sorted_list",sorted_list)

sorted_list [2, 3, 5, 7, 33, 57, 71, 99]


In [ ]:
a=[5,2,4,1]
for i in range(len(a)):
 for j in range(len(a)-1):
  if a[j]>a[j+1]:
    a[j+1],a[j]=a[j],a[j+1]

print(a)

[1, 2, 4, 5]


In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [55 66 76 88]]


In [ ]:
import numpy as np
data2=[[1,2,3,4]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(1, 4)
[[1 2 3 4]]


In [ ]:
a=np.array([[0,1,2],[2,3,4]])
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
ar=np.zeros((4,4))
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ar=np.ones((4,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ar=np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar=np.arange(0,20,3)
ar

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
ar=np.random.randint(0,20,(4,2))
ar

array([[ 6,  0],
       [19, 17],
       [11,  8],
       [ 9, 18]])

In [ ]:
arr=np.array([[1.,2.,3.,],[4.,5.,6.,]])
print(arr)

print(arr*arr)

print(arr-arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=2
arr=np.random.randint(0,20,(4,4))
print(arr)


print(arr*a)


print((arr*a)-arr)

[[ 3 15  8  8]
 [ 3 12 15 17]
 [ 6  3  8  1]
 [ 5 14 17 13]]
[[ 6 30 16 16]
 [ 6 24 30 34]
 [12  6 16  2]
 [10 28 34 26]]
[[ 3 15  8  8]
 [ 3 12 15 17]
 [ 6  3  8  1]
 [ 5 14 17 13]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr**2)
#Comparisons between arrays of the same size yield boolean arrays:
arr2=np.array([[0,4,1],[7,2,12]])
print(arr2)
print(arr2>arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 0  4  1]
 [ 7  2 12]]
[[False  True False]
 [ True False  True]]


In [ ]:
arr=np.random.randint(0,20,(3,3))
arr=np.random.randint(0,20,(3,3))
print(arr)

print(arr2)

print(arr>arr2)


[[16  1 11]
 [ 5 18 19]
 [19 16  9]]
[[1 2 3]
 [3 4 2]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
import numpy as np
print("enter row size")
r=int(input())
print("enter the coloumn")
c=int(input())
ar=np.random.randint(0,50,(r,c))
print(ar)

enter row size
2
enter the coloumn
2
[[42 48]
 [35  8]]


In [ ]:
# GCD of two nos using recursion
def gcd_fun(x,y):
  if(y==0):
    return x
  else:
    return gcd_fun(y,x%y)
x=int(input("Enter the first no:"))
y=int(input("Enter the second no:"))
num=gcd_fun(x,y)
print("GCD of two nos is:")
print(num)

Enter the first no:3
Enter the second no:2
GCD of two nos is:
1


In [8]:
# Linear Search
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1
arr = [4, 2, 8, 1, 5, 9, 3]
target = 5
result = linear_search(arr, target)
if result != -1:
    print(f"Element {target} is present at index {result}.")
else:
    print(f"Element {target} is not present in the array.")

Element 5 is present at index 4.


In [15]:
# Binary Search
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
target = 7
result = binary_search(arr, target)
if result != -1:
    print(f"Element {target} is present at index {result}.")
else:
    print(f"Element {target} is not present in the array.")

Element 7 is present at index 6.
